In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [33]:
df = pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [54]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

# Analisis exploratorio de datos (20)

In [34]:
# verificar valores faltantes
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [35]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [36]:
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [45]:
# balanceo de datos
from sklearn.utils import resample

df_clase_0 = df[df['Outcome'] == 0]
df_clase_1 = df[df['Outcome'] == 1]

df_clase_1_sobremuestreada = resample(df_clase_1, replace=True, n_samples=len(df_clase_0), random_state=42)

df_balanceado = pd.concat([df_clase_0, df_clase_1_sobremuestreada])


df_balanceado = df_balanceado.sample(frac=1, random_state=42)

df_balanceado['Outcome'].value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [ ]:
#preprocesamiento de datos

In [50]:
#entrenamiento del modeloo

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV



X = df_balanceado.drop('Outcome', axis=1)
y = df_balanceado['Outcome']

# datos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

svm_model = SVC(C=1.0, kernel='rbf', gamma='scale')

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("PrecisiÃ³n del modelo SVM: {:.2f}%".format(accuracy * 100))

PrecisiÃ³n del modelo SVM: 66.00%

In [53]:
import pickle

# Supongamos que tienes un modelo SVM llamado svm_model

# Guardar el modelo en un archivo pickle
filename = 'modelo_svm.pkl'
with open(filename, 'wb') as file:
    pickle.dump(svm_model, file)